/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentDir;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author joven
 */
public class AdminFormSignUp extends javax.swing.JInternalFrame {

    private Component frame;

    /**
     * Creates new form AdminForm
     */
    public AdminFormSignUp() {
        initComponents();
        ALname.setDocument(new JTextFieldLimit(20));
        AFname.setDocument(new JTextFieldLimit(20));
        AMname.setDocument(new JTextFieldLimit(2));
        AAge.setDocument(new JTextFieldLimit(2));
        AContact.setDocument(new JTextFieldLimit(11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ALname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AFname = new javax.swing.JTextField();
        AMname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AContact = new javax.swing.JTextField();
        AUser = new javax.swing.JTextField();
        AGender = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ACancelButton = new javax.swing.JButton();
        APass = new javax.swing.JPasswordField();
        APass1 = new javax.swing.JPasswordField();
        AAge = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add Administrator"));
        setTitle("Administrator Form");
        setAlignmentX(200.0F);
        setAlignmentY(200.0F);

        jLabel1.setText("Name");

        ALname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALnameActionPerformed(evt);
            }
        });
        ALname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ALnameKeyTyped(evt);
            }
        });

        jLabel2.setText("Last Name");

        AFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AFnameKeyTyped(evt);
            }
        });

        AMname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AMnameKeyTyped(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("MI");

        jLabel5.setText("Age");

        jLabel6.setText("Gender");

        jLabel7.setText("Contact #");

        jLabel8.setText("Username");

        jLabel9.setText("Password");

        jLabel10.setText("Repeat Password");

        AContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AContactActionPerformed(evt);
            }
        });
        AContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AContactKeyTyped(evt);
            }
        });

        AGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ACancelButton.setText("Cancel");
        ACancelButton.setEnabled(false);
        ACancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACancelButtonActionPerformed(evt);
            }
        });

        AAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAgeActionPerformed(evt);
            }
        });
        AAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AAgeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(ACancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(72, 72, 72)
                                        .addComponent(ALname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AFname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AGender, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AUser)
                                            .addComponent(AContact, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(APass)
                                            .addComponent(APass1)
                                            .addComponent(AAge, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AMname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ALname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(AGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(APass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(APass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(ClearButton)
                    .addComponent(ACancelButton))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        setBounds(250, 50, 634, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

        ALname.setText("");
        AFname.setText("");
        AMname.setText("");
        AAge.setText("");
        AGender.setSelectedItem(1);
        AContact.setText("");
        AUser.setText("");
        APass.setText("");
        APass1.setText("");
        ALname.requestFocusInWindow();
        ALname.selectAll();

// TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ACancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ACancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "admin_dbs";
        Statement stmt = null;
        ResultSet res = null;
        ResultSet result = null;
        String driver = "com.mysql.jdbc.Driver";
        String databaseUserName = "user1";
        String databasePassword = "test";
        
        
        if(ALname.getText().equals("") || AFname.getText().equals("") || AMname.getText().equals("") || AAge.getText().equals("") || AContact.getText().equals("") || AUser.getText().equals("") || APass.getText().equals("") || APass1.getText().equals("")){
            
            JOptionPane.showMessageDialog(frame, "Please fill in empty fields!");
            
        }else{
            
            if(APass.getText().length() < 6){
                   JOptionPane.showMessageDialog(frame, "Password must be six or more characters!");
                   APass.setText("");
                   APass1.setText("");
            } else{
            
        String lname = ALname.getText();
        String fname = AFname.getText();
        String mname = AMname.getText();
        String age = AAge.getText();
        String gender = AGender.getSelectedItem() + "";
        String contact = AContact.getText();
        String user = AUser.getText();
        String pass = APass.getText();
        String pass1 = APass1.getText();
 
            if(pass.equals(pass1)){       
            try {
                conn = DriverManager.getConnection(url + dbName, databaseUserName, databasePassword);
                stmt = conn.createStatement();
                result = null;
                System.out.println("Connection Passed!");

                } catch (Exception e) {
                        e.printStackTrace();
                }
            try{

            String sql1 = "SELECT * FROM allusers WHERE username = ?";
            PreparedStatement st1 = conn.prepareStatement(sql1);
            
            st1 = conn.prepareStatement(sql1);
            st1.setString(1, AUser.getText());
            res = st1.executeQuery();
            if(res.next()){
                JOptionPane.showMessageDialog(frame, "Username already exist!");
                AUser.requestFocusInWindow();
                AUser.selectAll();
                System.out.println("Data is present in allusers table");
            }else{
            try {

            String sql = "INSERT INTO administrator (lastname, firstname, middlename, age, gender, contactno, username, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, lname);
            st.setString(2, fname);
            st.setString(3, mname);
            st.setString(4, age);
            st.setString(5, gender);
            st.setString(6, contact);
            st.setString(7, user);
            st.setString(8, pass);
            st.executeUpdate();
            
            String sql2 = "INSERT INTO allusers (lastname, firstname, middlename, age, gender, contactno, username, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement st2 = conn.prepareStatement(sql2);

            st2.setString(1, lname);
            st2.setString(2, fname);
            st2.setString(3, mname);
            st2.setString(4, age);
            st2.setString(5, gender);
            st2.setString(6, contact);
            st2.setString(7, user);
            st2.setString(8, pass);
            st2.executeUpdate();

            JOptionPane.showMessageDialog(frame, "Administrator Successfully Added!");
            conn.close();

            ALname.setText("");
            AFname.setText("");
            AMname.setText("");
            AAge.setText("");
            AGender.setSelectedItem(1);
            AContact.setText("");
            AUser.setText("");
            APass.setText("");
            APass1.setText("");
            
            MainFrame1 mf1 = new MainFrame1();
            mf1.show();
            ((JFrame)this.getTopLevelAncestor()).dispose();
            

            } catch (Exception ex) {
            JOptionPane.showMessageDialog(frame, "Username already exist!");
            AUser.requestFocusInWindow();
            AUser.selectAll();
            System.out.println("SQL Error for main data insertion.");

            }
            } //else
            
        } catch(Exception e){
            
            JOptionPane.showMessageDialog(frame, "Username already exist!");
            AUser.requestFocusInWindow();
            AUser.selectAll();
            System.out.println("SQL error for table allusers");
            
         }
            }
    else{
    JOptionPane.showMessageDialog(frame, "Password did not match!");
            APass.setText("");
            APass1.setText("");
    }
            }
        
    }//GEN-LAST:event_SaveButtonActionPerformed
    }
    private void ALnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALnameActionPerformed

    private void AContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AContactActionPerformed

    private void AContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AContactKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        }   
        
    }//GEN-LAST:event_AContactKeyTyped

    private void AAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AAgeKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_AAgeKeyTyped

    private void ALnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ALnameKeyTyped

         char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_ALnameKeyTyped

    private void AFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AFnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_AFnameKeyTyped

    private void AMnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AMnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_AMnameKeyTyped

    private void AAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AAgeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AAge;
    private javax.swing.JButton ACancelButton;
    private javax.swing.JTextField AContact;
    private javax.swing.JTextField AFname;
    private javax.swing.JComboBox AGender;
    private javax.swing.JTextField ALname;
    private javax.swing.JTextField AMname;
    private javax.swing.JPasswordField APass;
    private javax.swing.JPasswordField APass1;
    private javax.swing.JTextField AUser;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
