/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentDir;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ash
 */
public class LoginForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LoginCmd = new javax.swing.JButton();
        CancelCmd = new javax.swing.JButton();
        AccountType = new javax.swing.JComboBox();
        APass = new javax.swing.JPasswordField();
        ForgotPassCmd = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Login Form"));
        setTitle("Student Directory Portal");
        setVisible(true);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        LoginCmd.setText("Login");
        LoginCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCmdActionPerformed(evt);
            }
        });

        CancelCmd.setText("Cancel");
        CancelCmd.setEnabled(false);
        CancelCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCmdActionPerformed(evt);
            }
        });

        AccountType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "LevelOne", "LevelTwo" }));

        ForgotPassCmd.setText("Forgot Password");
        ForgotPassCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPassCmdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ForgotPassCmd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(LoginCmd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelCmd))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(AUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(APass))))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(AUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(APass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelCmd)
                    .addComponent(LoginCmd)
                    .addComponent(ForgotPassCmd))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setBounds(350, 150, 385, 256);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCmdActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelCmdActionPerformed

    private void LoginCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCmdActionPerformed

        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "admin_dbs";
        Statement stmt = null;
        ResultSet result = null;
        String driver = "com.mysql.jdbc.Driver";
        String databaseUserName = "user1";
        String databasePassword = "test";
        
        try{
        conn = DriverManager.getConnection(url + dbName, databaseUserName, databasePassword);
        stmt = conn.createStatement();
        System.out.println("Connected to the database.");
        }catch(Exception e){
            System.out.println("Failed to connect ot the database.");
        }
        
        
          if(AUser.getText().equals("") || APass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in empty fields!");
        }else{
        
        String acct = AccountType.getSelectedItem() + "";
        accountType selected = accountType.valueOf(acct);
        switch(selected){
            
            case Administrator:
                try{
                String sql = "SELECT * FROM administrator WHERE username = ? and password = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st=conn.prepareStatement(sql);
                st.setString(1, AUser.getText());
                st.setString(2, APass.getText());
                result=st.executeQuery();
                             if(result.next()){
                               JOptionPane.showMessageDialog(null, "Login Successful!");
                               System.out.println("Logged In Admin");
                               
                               AdminFrame af = new AdminFrame();
                               af.setVisible(true);
                               ((JFrame)this.getTopLevelAncestor()).dispose();
                             }else{
                               JOptionPane.showMessageDialog(null, "Login Failed: Check Username/Password and Account Level!");
                               System.out.println("Fail Log In Admin");
                             }
                }catch(Exception e){
                    System.out.println("Administrator: Attempt failed to log in.");
                    JOptionPane.showMessageDialog(null, "Username doesn't exist!");
                }
                break;
                
                
            case LevelOne:
                try{
                String sql = "SELECT * FROM levelone WHERE username = ? and password = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st=conn.prepareStatement(sql);
                st.setString(1, AUser.getText());
                st.setString(2, APass.getText());
                result=st.executeQuery();
                             if(result.next()){
                               JOptionPane.showMessageDialog(null, "Login Successful!");
                               LevelOneFrame lof = new LevelOneFrame();
                               lof.setVisible(true);
                               ((JFrame)this.getTopLevelAncestor()).dispose();
                               System.out.println("Logged In Level 1");
                             }else{
                               JOptionPane.showMessageDialog(null, "Login Failed: Check Username/Password and Account Level!");
                               System.out.println("Fail Log In Level 1");
                             }
                }catch(Exception e){
                    System.out.println("Level 1: Attempt failed to log in.");
                    LevelOneFrame lof = new LevelOneFrame();
                    lof.setVisible(true);
                    ((JFrame)this.getTopLevelAncestor()).dispose();
                    JOptionPane.showMessageDialog(null, "Username doesn't exist!");
                }
                break;
                
            case LevelTwo:              
                try{
                String sql = "SELECT * FROM leveltwo WHERE username = ? and password = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st=conn.prepareStatement(sql);
                st.setString(1, AUser.getText());
                st.setString(2, APass.getText());
                result=st.executeQuery();
                             if(result.next()){
                               JOptionPane.showMessageDialog(null, "Login Successful!");
                               LevelTwoFrame ltf = new LevelTwoFrame();
                               ltf.setVisible(true);
                               ((JFrame)this.getTopLevelAncestor()).dispose();
                               System.out.println("Logged In Level 2");
                             }else{
                               JOptionPane.showMessageDialog(null, "Login Failed: Check Username/Password and Account Level!");
                               System.out.println("Fail Log In Level 2");
                             }
                }catch(Exception e){
                    System.out.println("Level 2: Attempt failed to log in.");
                    JOptionPane.showMessageDialog(null, "Username doesn't exist!");
                }
                break;
        }
        
        }
    }//GEN-LAST:event_LoginCmdActionPerformed

    private void ForgotPassCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPassCmdActionPerformed
        
        ForgotPassForm fpf = new ForgotPassForm();
        JDesktopPane MainDesk = this.getDesktopPane();
        MainDesk.add(fpf);
        this.dispose();
        fpf.show();
    }//GEN-LAST:event_ForgotPassCmdActionPerformed

    private enum accountType{
    
        Administrator,
        LevelOne,
        LevelTwo
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField APass;
    private javax.swing.JTextField AUser;
    private javax.swing.JComboBox AccountType;
    private javax.swing.JButton CancelCmd;
    private javax.swing.JButton ForgotPassCmd;
    private javax.swing.JButton LoginCmd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
