/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentDir;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ash
 */
public class SearchStud extends javax.swing.JInternalFrame {
    private Component frame;

    /**
     * Creates new form AddStudent
     */
    public SearchStud() {
        initComponents();
        
        studno.setDocument(new JTextFieldLimit(8));
        lastname.setDocument(new JTextFieldLimit(20));
        firstname.setDocument(new JTextFieldLimit(20));
        middlename.setDocument(new JTextFieldLimit(2));
        age.setDocument(new JTextFieldLimit(2));
        section.setDocument(new JTextFieldLimit(4));
        guardian.setDocument(new JTextFieldLimit(30));
        contactno.setDocument(new JTextFieldLimit(11));
        address.setDocument(new JTextFieldLimit(100));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        guardian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        ClearCmd = new javax.swing.JButton();
        CancelCmd = new javax.swing.JButton();
        course = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        SearchCmd = new javax.swing.JButton();
        ImageFrame = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Search Student"));
        setTitle("Search Student Info");

        jLabel1.setText("Student Number");

        studno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studnoKeyTyped(evt);
            }
        });

        jLabel2.setText("Name");

        lastname.setEditable(false);
        lastname.setEnabled(false);
        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameKeyTyped(evt);
            }
        });

        firstname.setEditable(false);
        firstname.setEnabled(false);
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });

        middlename.setEditable(false);
        middlename.setEnabled(false);
        middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middlenameKeyTyped(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel4.setText("First Name");

        jLabel5.setText("MI");

        jLabel6.setText("Age");

        age.setEditable(false);
        age.setEnabled(false);
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        jLabel7.setText("Birthday(mmDDyyyy)");

        jLabel8.setText("Gender");

        jLabel9.setText("Course");

        jLabel10.setText("Section");

        section.setEditable(false);
        section.setEnabled(false);

        jLabel11.setText("Guardian");

        guardian.setEditable(false);
        guardian.setEnabled(false);

        jLabel12.setText("Contact #");

        contactno.setEditable(false);
        contactno.setEnabled(false);
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoKeyTyped(evt);
            }
        });

        jLabel13.setText("Address");

        address.setEditable(false);
        address.setEnabled(false);

        ClearCmd.setText("Clear");
        ClearCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearCmdActionPerformed(evt);
            }
        });

        CancelCmd.setText("Cancel");
        CancelCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCmdActionPerformed(evt);
            }
        });

        course.setEditable(false);
        course.setEnabled(false);

        gender.setEditable(false);
        gender.setEnabled(false);

        birthday.setEditable(false);
        birthday.setEnabled(false);

        SearchCmd.setText("Search");
        SearchCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCmdActionPerformed(evt);
            }
        });

        ImageFrame.setBackground(java.awt.Color.white);
        ImageFrame.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gender)
                                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(section)
                                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(studno)
                                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SearchCmd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ClearCmd))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel3)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CancelCmd)
                                    .addComponent(middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(contactno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(guardian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel13)
                        .addGap(83, 83, 83)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(studno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchCmd)
                            .addComponent(ClearCmd)
                            .addComponent(CancelCmd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        setBounds(210, 30, 702, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCmdActionPerformed

        this.dispose();
    }//GEN-LAST:event_CancelCmdActionPerformed

    private void ClearCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearCmdActionPerformed

        studno.setText("");
        lastname.setText("");
        firstname.setText("");
        middlename.setText("");
        age.setText("");
        birthday.setText("");
        gender.setText("");
        course.setText("");
        section.setText("");
        guardian.setText("");
        contactno.setText("");
        address.setText("");
        ImageFrame.setIcon(null);
        studno.requestFocusInWindow();
        studno.selectAll();
        
            lastname.setEnabled(false);
            firstname.setEnabled(false);
            middlename.setEnabled(false);
            age.setEnabled(false);
            birthday.setEnabled(false);
            gender.setEnabled(false);
            course.setEnabled(false);
            section.setEnabled(false);
            guardian.setEnabled(false);
            contactno.setEnabled(false);
            address.setEnabled(false);
        
    }//GEN-LAST:event_ClearCmdActionPerformed

    private void studnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studnoKeyTyped
        
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_studnoKeyTyped

    private void lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_lastnameKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_ageKeyTyped

    private void contactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_contactnoKeyTyped

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_firstnameKeyTyped

    private void middlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middlenameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_middlenameKeyTyped

    private void SearchCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCmdActionPerformed
        
        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "students_dbs";
        Statement stmt = null;
        ResultSet result = null;
        String driver = "com.mysql.jdbc.Driver";
        String databaseUserName = "user1";
        String databasePassword = "test";
        
        try{
        
        conn = DriverManager.getConnection(url + dbName, databaseUserName, databasePassword);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM student WHERE studentno = ?";
        PreparedStatement st = conn.prepareStatement(sql);    
            
        st=conn.prepareStatement(sql);
	st.setString(1, studno.getText());
        if(studno.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please fill empty fields!");
            
        }else
                
            result=st.executeQuery();
            if(result.next()){
            
            lastname.setEnabled(true);
            firstname.setEnabled(true);
            middlename.setEnabled(true);
            age.setEnabled(true);
            birthday.setEnabled(true);
            gender.setEnabled(true);
            course.setEnabled(true);
            section.setEnabled(true);
            guardian.setEnabled(true);
            contactno.setEnabled(true);
            address.setEnabled(true);
                
            lastname.setText(result.getString(2)); 
            firstname.setText(result.getString(3));
            middlename.setText(result.getString(4));
            age.setText(result.getString(5));
            birthday.setText(result.getString(6));
            gender.setText(result.getString(7));
            course.setText(result.getString(8));
            section.setText(result.getString(9));
            guardian.setText(result.getString(10));
            contactno.setText(result.getString(11));
            address.setText(result.getString(12));
            byte[] imagedata = result.getBytes("image");
            BufferedImage buff_image = ImageIO.read(new ByteArrayInputStream(imagedata));
            format = new ImageIcon(buff_image);
            ImageFrame.setIcon(format);
            studno.requestFocusInWindow();
            studno.selectAll();

            }else{

            JOptionPane.showMessageDialog(null, "Student Number does not exist!");
            studno.requestFocusInWindow();
            studno.selectAll();

            }


}catch (Exception e){

	System.out.println("Failed to connect.");
}
        
    }//GEN-LAST:event_SearchCmdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelCmd;
    private javax.swing.JButton ClearCmd;
    private javax.swing.JLabel ImageFrame;
    private javax.swing.JButton SearchCmd;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField course;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField guardian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField middlename;
    private javax.swing.JTextField section;
    private javax.swing.JTextField studno;
    // End of variables declaration//GEN-END:variables

    
    String filename = null;
    private ImageIcon format = null;
    byte[] person_name = null;
    
}
