/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentDir;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ash
 */
public class UpdStudent extends javax.swing.JInternalFrame {
    private Component frame;

    /**
     * Creates new form AddStudent
     */
    public UpdStudent() {
        initComponents();
        
        studno.setDocument(new JTextFieldLimit(8));
        lastname.setDocument(new JTextFieldLimit(20));
        firstname.setDocument(new JTextFieldLimit(20));
        middlename.setDocument(new JTextFieldLimit(2));
        age.setDocument(new JTextFieldLimit(2));
        section.setDocument(new JTextFieldLimit(4));
        guardian.setDocument(new JTextFieldLimit(30));
        contactno.setDocument(new JTextFieldLimit(11));
        address.setDocument(new JTextFieldLimit(100));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        guardian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        UpdCmd = new javax.swing.JButton();
        ClearCmd = new javax.swing.JButton();
        CancelCmd = new javax.swing.JButton();
        SearchCmd = new javax.swing.JButton();
        birthday = new javax.swing.JFormattedTextField();
        course1 = new javax.swing.JComboBox();
        gender1 = new javax.swing.JComboBox();
        course = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        ImageFrame = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Update Student"));
        setTitle("Update Student Info");

        jLabel1.setText("Student Number");

        studno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studnoKeyTyped(evt);
            }
        });

        jLabel2.setText("Name");

        lastname.setEnabled(false);
        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameKeyTyped(evt);
            }
        });

        firstname.setEnabled(false);
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });

        middlename.setEnabled(false);
        middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middlenameKeyTyped(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel4.setText("First Name");

        jLabel5.setText("MI");

        jLabel6.setText("Age");

        age.setEnabled(false);
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        jLabel7.setText("Birthday(mmDDyyyy)");

        jLabel8.setText("Gender");

        jLabel9.setText("Course");

        jLabel10.setText("Section");

        section.setEnabled(false);

        jLabel11.setText("Guardian");

        guardian.setEnabled(false);
        guardian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guardianKeyTyped(evt);
            }
        });

        jLabel12.setText("Contact #");

        contactno.setEnabled(false);
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoKeyTyped(evt);
            }
        });

        jLabel13.setText("Address");

        address.setEnabled(false);

        UpdCmd.setText("Update");
        UpdCmd.setEnabled(false);
        UpdCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdCmdActionPerformed(evt);
            }
        });

        ClearCmd.setText("Clear");
        ClearCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearCmdActionPerformed(evt);
            }
        });

        CancelCmd.setText("Cancel");
        CancelCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCmdActionPerformed(evt);
            }
        });

        SearchCmd.setText("Search");
        SearchCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCmdActionPerformed(evt);
            }
        });

        try {
            birthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        birthday.setText("mm/dd/yyyy");
        birthday.setEnabled(false);

        course1.setEditable(true);
        course1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BSCS", "BSN", "BSEd", "HRM" }));
        course1.setEnabled(false);

        gender1.setEditable(true);
        gender1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender1.setEnabled(false);

        course.setEditable(false);
        course.setEnabled(false);
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        gender.setEditable(false);
        gender.setEnabled(false);

        ImageFrame.setBackground(java.awt.Color.white);
        ImageFrame.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(85, 85, 85)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(101, 101, 101)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(SearchCmd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel4)
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(UpdCmd)
                            .addGap(13, 13, 13)
                            .addComponent(ClearCmd)
                            .addGap(3, 3, 3)
                            .addComponent(CancelCmd))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(77, 77, 77))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(71, 71, 71)))
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(guardian, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SearchCmd))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdCmd)
                    .addComponent(ClearCmd)
                    .addComponent(CancelCmd))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        setBounds(200, 20, 721, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCmdActionPerformed

        this.dispose();
    }//GEN-LAST:event_CancelCmdActionPerformed

    private void ClearCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearCmdActionPerformed

        studno.setText("");
        lastname.setText("");
        firstname.setText("");
        middlename.setText("");
        age.setText("");
        birthday.setText("");
        gender.setText("");
        gender1.setSelectedItem(null);
        course.setText("");
        course1.setSelectedItem(null);
        section.setText("");
        guardian.setText("");
        contactno.setText("");
        address.setText("");
        ImageFrame.setIcon(null);
        
            studno.setEnabled(true);
            lastname.setEnabled(false);
            firstname.setEnabled(false);
            middlename.setEnabled(false);
            age.setEnabled(false);
            birthday.setEnabled(false);
            gender.setEnabled(false);
            gender1.setEnabled(false);
            course.setEnabled(false);
            course1.setEnabled(false);
            section.setEnabled(false);
            guardian.setEnabled(false);
            contactno.setEnabled(false);
            address.setEnabled(false);
            UpdCmd.setEnabled(false);   
                    studno.requestFocusInWindow();
                    studno.selectAll();
    }//GEN-LAST:event_ClearCmdActionPerformed

    private void UpdCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdCmdActionPerformed
        
        Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "students_dbs";
        Statement stmt = null;
        ResultSet result = null;
        String driver = "com.mysql.jdbc.Driver";
        String databaseUserName = "user1";
        String databasePassword = "test";
        
        if(studno.getText().equals("")){
             JOptionPane.showMessageDialog(frame, "Nothing to update, Search field is empty!");
        }else{
                        
           try {
                conn = DriverManager.getConnection(url + dbName, databaseUserName, databasePassword);
                stmt = conn.createStatement();
                result = null;
                System.out.println("Connection Passed!");

                } catch (Exception e) {
                        System.out.println("Failed to connect to the database.");
                }
           //end connection database testing
           

               int x = JOptionPane.showConfirmDialog(frame, "Are you sure you want to update this record?");
               if(x==0){           
            
            
            try {    
            String sql = "UPDATE student set studentno='" + studno.getText() + "',lastname='" + lastname.getText() + "',firstname='" + firstname.getText() + "',middlename='" + middlename.getText() + "',age='" + age.getText() + "',birthday='" + birthday.getText() + "',gender='" + gender1.getSelectedItem() + ""  + "',course='" + course1.getSelectedItem() + "" + "',section='" + section.getText() + "',guardian='" + guardian.getText() + "',contactno='" + contactno.getText() + "',address='" + address.getText() + "' WHERE studentno='" + studno.getText() + "'";
           
            PreparedStatement st = conn.prepareStatement(sql);
            st.execute();
            
            JOptionPane.showMessageDialog(frame, "Student Info Successfully Updated!");
            conn.close();

            studno.setText("");
            lastname.setText("");
            firstname.setText("");
            middlename.setText("");
            age.setText("");
            birthday.setText("");
            gender.setText("");
            gender1.setSelectedItem(null);
            course.setText("");
            course1.setSelectedItem(null);
            section.setText("");
            guardian.setText("");
            contactno.setText("");
            address.setText("");
            ImageFrame.setIcon(null);
            studno.requestFocusInWindow();
            studno.selectAll();
        
            studno.setEnabled(true);
            lastname.setEnabled(false);
            firstname.setEnabled(false);
            middlename.setEnabled(false);
            age.setEnabled(false);
            birthday.setEnabled(false);
            gender.setEnabled(false);
            gender1.setEnabled(false);
            course.setEnabled(false);
            course1.setEnabled(false);
            section.setEnabled(false);
            guardian.setEnabled(false);
            contactno.setEnabled(false);
            address.setEnabled(false);
            UpdCmd.setEnabled(false);
            
           }catch(Exception e){
             System.out.println("SQL Error for updating student record");
             JOptionPane.showMessageDialog(frame, "Something went wrong in updating this record!");
             studno.requestFocusInWindow();
             studno.selectAll();
           }
               }
           //end try-catch for database main deletion
                        
                        
        }//else end if no empty fields
      
        
        //savecmd end--
    }//GEN-LAST:event_UpdCmdActionPerformed

    private void studnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studnoKeyTyped
        
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_studnoKeyTyped

    private void lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_lastnameKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_ageKeyTyped

    private void contactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_contactnoKeyTyped

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_firstnameKeyTyped

    private void middlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middlenameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
        
    }//GEN-LAST:event_middlenameKeyTyped

    private void SearchCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCmdActionPerformed
        
        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "students_dbs";
        Statement stmt = null;
        ResultSet result = null;
        String driver = "com.mysql.jdbc.Driver";
        String databaseUserName = "user1";
        String databasePassword = "test";
        
        try{
        
        conn = DriverManager.getConnection(url + dbName, databaseUserName, databasePassword);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM student WHERE studentno = ?";
        PreparedStatement st = conn.prepareStatement(sql);    
            
        st=conn.prepareStatement(sql);
	st.setString(1, studno.getText());
        if(studno.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please fill empty fields!");
            
        }else
            
            result=st.executeQuery();
            if(result.next()){
            
            studno.setEnabled(false);
            lastname.setEnabled(true);
            firstname.setEnabled(true);
            middlename.setEnabled(true);
            age.setEnabled(true);
            birthday.setEnabled(true);
            gender1.setEnabled(true);
            course1.setEnabled(true);
            section.setEnabled(true);
            guardian.setEnabled(true);
            contactno.setEnabled(true);
            address.setEnabled(true);
            
            
                
            lastname.setText(result.getString(2)); 
            firstname.setText(result.getString(3));
            middlename.setText(result.getString(4));
            age.setText(result.getString(5));
            birthday.setText(result.getString(6));
            gender.setText(result.getString(7));
            course.setText(result.getString(8));
            section.setText(result.getString(9));
            guardian.setText(result.getString(10));
            contactno.setText(result.getString(11));
            address.setText(result.getString(12));
            byte[] imagedata = result.getBytes("image");
            BufferedImage buff_image = ImageIO.read(new ByteArrayInputStream(imagedata));
            format = new ImageIcon(buff_image);
            ImageFrame.setIcon(format);
            
            UpdCmd.setEnabled(true);

            }else{

            JOptionPane.showMessageDialog(null, "Student Number does not exist!");
            studno.requestFocusInWindow();
            studno.selectAll();

            }


}catch (Exception e){

	System.out.println("Failed to connect.");
}
        
    }//GEN-LAST:event_SearchCmdActionPerformed

    private void guardianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardianKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_guardianKeyTyped

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelCmd;
    private javax.swing.JButton ClearCmd;
    private javax.swing.JLabel ImageFrame;
    private javax.swing.JButton SearchCmd;
    private javax.swing.JButton UpdCmd;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JFormattedTextField birthday;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField course;
    private javax.swing.JComboBox course1;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField gender;
    private javax.swing.JComboBox gender1;
    private javax.swing.JTextField guardian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField middlename;
    private javax.swing.JTextField section;
    private javax.swing.JTextField studno;
    // End of variables declaration//GEN-END:variables
    String filename = null;
    private ImageIcon format = null;
    byte[] person_name = null;
    
}
